### ISSUE TITLE
Document the handshake process

### ISSUE THREAD

**Issue by rase-** [socketio/socket.io-protocol#10]
The documentation for the handshake process should be documented.

Originally requested here: https://github.com/Automattic/socket.io/issues/1577

**Comment by adamrothman** [comment]
+1 please, am in the process of writing an iOS client for 1.x and reverse engineering is hard.

**Comment by rauchg** [comment]
We should add here: https://github.com/Automattic/socket.io-protocol

**Comment by jgod** [comment]
+1. The lib is fantastic and all but the difficulty writing custom clients is stopping people from upgrading from 0.9.

**Comment by rauchg** [comment]
We are working on this atm as we are preparing a Java server implementation

**Comment by littlepedro78** [comment]
Any update??

**Comment by cacharrin** [comment]
I'm writing a custom client too... any update?

**Comment by thetrompf** [comment]
The system has been abstracted a lot, and split in to 2 parts (protocol-wise), so the handshake is not handled by the `socket.io-protocol` but by the `engine.io-protocol`.

**Comment by cacharrin** [comment]
Yep, i read the engine-io.protocol... i think its very abstract too...

**Comment by computersarecool** [comment]
+1

**Comment by steviesama** [comment]
I actually got through the first 2 completing the handshake, and the on connection emit actually fires and I pick it up in the serial monitor of my Arduino, but the third connection upgrade request I get bad request. So frustrating.

**Comment by NeoLegends** [comment]
The best way to write a client for this library is by capturing the network traffic using e.g. Wireshark and using the documents from `engine.io-protocol` and `socket.io-protocol` to work out something that works. It takes a while, but this is the best way to go, especially since some of the information in the protocol repos seems to be out of date.

**Comment by adamrothman** [comment]
It is crazy to me that the "best" way to write a client is _still_ (more than a year later) to reverse-engineer the protocol by reading the source of some other client or snooping packets. One would think the maintainers would want to encourage external development by offering as much documentation as possible. I gave up on my client implementation due to the lack of docs, and went another direction.

`¯\_(ツ)_/¯`

**Comment by NeoLegends** [comment]
Yeah, that hurts.

**Comment by rlmaso2** [comment]
Any update? Do you all plan to release a document detailing the handshake process?

**Comment by GimpMaster** [comment]
I'm assuming there still exists no documentation on the handshake and packet sniffing is the best course of action? Terrible if that is so.

**Comment by darrachequesne** [comment]
Please see here: https://github.com/socketio/engine.io-protocol/tree/v3#anatomy-of-an-engineio-session
